### Request 1: Create a New User ###
POST http://localhost:3000/posts/login
Content-Type: application/json

{
  "Email": "Mohammadshr@gmail.com",
  "Password": "1200643"
}

### Request 2: Create a New User ###
POST http://localhost:3000/posts/register
Content-Type: application/json

{
  "Email": "moeshai@gmail.com",
  "Password": "1234"
}

### Request 2: get campaigns###
GET http://localhost:3000/posts/campaign/662cf869bc1e80d9f47ef3ab
